---
- name: BIG-IP SETUP
  hosts: lb
  connection: local
  gather_facts: false

  tasks:
    - name: SAVE RUNNING CONFIG ON BIG-IP
      bigip_config:
        provider:
          server: "{{private_ip}}"
          user: "{{ansible_user}}"
          password: "{{ansible_password}}"
          server_port: 443
          validate_certs: false
        save: true
    - name: Send notify to Telegram
      community.general.telegram:
        token: '1881366819:AAEVMylIZiKE59dHIg7YqbKXIbonwrWOQGQ'
        api_args:
          chat_id: -588925616
          parse_mode: "markdown"
          text: "Your ADC has been backup"
          disable_web_page_preview: True
          disable_notification: True
