---
- name: BIG-IP SETUP
  hosts: lb
  connection: local
  gather_facts: false
  
  collections:
    - f5networks.f5_modules
    - community.general
  tasks:
    - name: SAVE RUNNING CONFIG ON BIG-IP
      bigip_config:
        provider:
          server: "{{private_ip}}"
          user: "{{ansible_user}}"
          password: "{{ansible_password}}"
          server_port: 443
          validate_certs: false
        save: true
