---
- name: "Check verify name of Pool and name of VirtualServer"
  hosts: lb
  connection: local
  gather_facts: false

  tasks:
    - name: Setup provider
      set_fact:
       provider:
        server: "{{private_ip}}"
        user: "{{ansible_user}}"
        password: "{{ansible_ssh_pass}}"
        server_port: "8443"
        validate_certs: "no"


  tasks:
    - name: View system version and LTM configuration
      bigip_command:
        commands:
          - list /ltm virtual "{{ virtual_name }}"
          - list /ltm pool "{{ pool_name }}"
      register: result

    - debug: msg="{{ result.stdout_lines }}"

...
